driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-6.8
  - name: centos-7.3
  - name: debian-7.11
  - name: debian-8.6
  - name: fedora-25
  - name: opensuse-leap-42.2
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
- name: default
  run_list:
  - recipe[ssh_known_hosts_test]
  attributes: {}
- name: cacher
  run_list:
  - recipe[ssh_known_hosts_test::cacher]
  attributes: {}
- name: cacher-client
  run_list:
  - recipe[ssh_known_hosts_test::default]
  attributes:
    ssh_known_hosts:
      use_data_bag_cache: true
- name: known_hosts_test
  run_list:
  - recipe[ssh_known_hosts_test::custom]
